import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  noEventsText: {
    textAlign: "center",
    fontWeight: 500,
    fontSize: 18,
    padding: 20,
  },
  monthYear: {
    color: "#fff",
    textAlign: "center",
    //margin: "auto",
    alignSelf: "center",
  },
  todayButton: {
    backgroundColor: "#1e7248",
    padding: 10,
    borderRadius: 5,
  },
  loader: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  news: {
    backgroundColor: "#fff",
  },
  sectionHeader: {
    backgroundColor: "#1b7248",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    paddingBottom: 30,
    paddingTop: 10,
  },
  title: {
    fontFamily: "RobotoRegular",
    width: "100%",
    color: "#fff",
    textAlign: "center",
    padding: 10,
    marginBottom: 20,
    marginTop: 15,
    fontSize: 21,
    borderRadius: 5,
    elevation: 0,
  },
  postWrap: {
    padding: 20,
    paddingTop: 0,
    backgroundColor: "#fff",
    maxWidth: "90%",
    //margin: "auto",
    alignSelf: "center",
    marginTop: -40,
    borderRadius: 5,
  },
  singlePostWrap: {
    padding: 10,
    paddingTop: 0,
    backgroundColor: "#0000002b",
    maxWidth: "90%",
    //margin: "auto",
    alignSelf: "center",
    marginTop: -40,
    borderRadius: 5,
  },
  eventsWrap: {
    padding: 5,
    backgroundColor: "#0000002b",
    maxWidth: "90%",
    //margin: "auto",
    alignSelf: "center",
    marginTop: -40,
    borderRadius: 5,
  },
  eventsItem: {
    marginBottom: 15,
    backgroundColor: "#ffffff",
    padding: 15,
    paddingTop: 0,
    fontFamily: "RobotoRegular",
    borderRadius: 10,
    shadowColor: "#333333",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 5,
    paddingTop: 10,
  },
  post: {
    marginBottom: 20,
    backgroundColor: "#ffffff",
    padding: 0,
    borderRadius: 8,
    fontFamily: "RobotoRegular",
    elevation: 1,
  },
  singlePostContent: {
    backgroundColor: "#fff",
    padding: 20,
    textAlign: "left",
  },
  singlePostTitle: {
    fontSize: 20,
    fontWeight: 500,
    color: "#000",
    backgroundColor: "#fff",
    marginTop: 20,
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
  },
  postTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: "#000",
  },
  postDate: {
    fontSize: 10,
    color: "#999999",
    marginTop: 10,
  },
  boxText: {
    fontFamily: "RobotoRegular",
    marginTop: 10,
    textAlign: "center",
    color: "#fff",
    textTransform: "uppercase",
    fontSize: 11,
    fontWeight: 500,
    lineHeight: 1,
  },
});

export default styles;
