import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  monthYear: {
    color: "#fff",
    textAlign: "center",
    margin: "auto",
  },
  loader: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  todayButton: {
    backgroundColor: "#1e7248",
    padding: 10,
    borderRadius: 5,
  },
  loader: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  news: {
    backgroundColor: "#fff",
  },
  sectionHeader: {
    backgroundColor: "#1b7248",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    paddingTop: 10,
  },
  title: {
    fontFamily: "RobotoRegular",
    width: "100%",
    color: "#fff",
    textAlign: "center",
    padding: 10,
    marginBottom: 15,
    marginTop: 15,
    fontSize: 24,
    borderRadius: 5,
    elevation: 0,
  },
  postWrap: {
    padding: 20,
    paddingTop: 0,
    backgroundColor: "#fff",
    maxWidth: "90%",
    //margin: "auto",
    alignSelf: "center",
    marginTop: -40,
    borderRadius: 5,
  },
  singlePostWrap: {
    padding: 10,
    paddingTop: 0,
    backgroundColor: "#0000002b",
    maxWidth: "90%",
    //margin: "auto",
    alignSelf: "center",
    marginTop: -40,
    borderRadius: 5,
  },
  eventsWrap: {
    padding: 5,
    backgroundColor: "#0000002b",
    maxWidth: "90%",
    //margin: "auto",
    alignSelf: "center",
    marginTop: -40,
    borderRadius: 5,
  },
  eventsItem: {
    marginBottom: 10,
    backgroundColor: "#ffffff",
    padding: 15,
    paddingTop: 0,
    borderRadius: 8,
    fontFamily: "RobotoRegular",
    elevation: 1,
  },
  post: {
    marginBottom: 20,
    backgroundColor: "#ffffff",
    padding: 0,
    borderRadius: 8,
    fontFamily: "RobotoRegular",
    elevation: 1,
  },
  singlePostContent: {
    backgroundColor: "#fff",
    padding: 20,
    textAlign: "left",
  },
  singlePostTitle: {
    fontSize: 20,
    fontWeight: 500,
    color: "#000",
    backgroundColor: "#fff",
    marginTop: 20,
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
  },
  postTitle: {
    fontSize: 20,
    fontWeight: 500,
    color: "#000",
  },
  postDate: {
    fontSize: 12,
    color: "#999999",
    marginTop: 10,
  },
  boxText: {
    fontFamily: "RobotoRegular",
    marginTop: 10,
    textAlign: "center",
    color: "#fff",
    textTransform: "uppercase",
    fontSize: 11,
    fontWeight: 500,
    lineHeight: 11,
  },
  settingsSectionHeader: {
    backgroundColor: "#4b5568",
    padding: 15,
  },
  settingsSectionHeaderTitle: {
    color: "#fff",
    fontSize: 20,
    letterSpacing: 0.15,
    textAlign: "center",
  },
  date: {
    fontWeight: 900,
    marginBottom: 5,
  },
  sourceOptions: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 20,
  },
  selectedButton: {
    borderColor: "#1d7249",
  },
  dummyTextContainer: {
    padding: 10,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    marginVertical: 10,
    alignItems: "center",
  },
  sourceButton: {
    padding: 10,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    fontWeight: 600,
  },
  selectedButton: {
    borderColor: "#000",
    borderWidth: 3,
  },
});

export default styles;
